#!/bin/bash
# =============================================================
# detect-env.sh — 探测当前设备环境，生成 local-env.sh
# 由 bootstrap.sh 调用，或手动执行
# =============================================================
CLAUDE_DIR="$HOME/.claude"
ENV_FILE="$CLAUDE_DIR/local-env.sh"

# ── 探测 Python ──────────────────────────────────────────────
# 优先选有 pip 安装包的 Python（跳过 Windows Store 空壳）
PYTHON_CMD=""
for candidate in python py python3; do
    if command -v "$candidate" &>/dev/null 2>&1; then
        # 验证 Python 3.8+ 且能正常导入包（非 Windows Store 空壳）
        if "$candidate" -c "import sys, pathlib; assert sys.version_info >= (3,8)" &>/dev/null 2>&1; then
            # 检查是否是有效的 pip 环境（能 import pip）
            if "$candidate" -m pip --version &>/dev/null 2>&1; then
                PYTHON_CMD="$candidate"
                break
            fi
        fi
    fi
done

# ── 探测 pip ─────────────────────────────────────────────────
PIP_CMD=""
for candidate in pip pip3; do
    if command -v "$candidate" &>/dev/null 2>&1; then
        PIP_CMD="$candidate"
        break
    fi
done

# ── 探测 OS ──────────────────────────────────────────────────
OS_TYPE="$(uname -s 2>/dev/null || echo 'Windows')"
case "$OS_TYPE" in
    Darwin*) OS_NAME="macos" ;;
    Linux*)  OS_NAME="linux" ;;
    MINGW*|MSYS*|CYGWIN*) OS_NAME="windows" ;;
    *)       OS_NAME="unknown" ;;
esac

# ── 写入 local-env.sh ────────────────────────────────────────
cat > "$ENV_FILE" << ENVEOF
# Auto-generated by detect-env.sh — DO NOT EDIT
# Re-run: bash ~/.claude/scripts/detect-env.sh
export CLAUDE_PYTHON="${PYTHON_CMD:-python}"
export CLAUDE_PIP="${PIP_CMD:-pip}"
export CLAUDE_OS="${OS_NAME}"
ENVEOF

echo "[detect-env] Python=${PYTHON_CMD:-NOT FOUND}, pip=${PIP_CMD:-NOT FOUND}, OS=${OS_NAME}"
echo "[detect-env] Saved to ${ENV_FILE}"
