#!/bin/bash
# =============================================================
# detect-env.sh — Detect current device environment, generate local-env.sh
# Called by bootstrap.sh or run manually
# =============================================================
CLAUDE_DIR="$HOME/.claude"
ENV_FILE="$CLAUDE_DIR/local-env.sh"

# -- Detect Python --
# Prefer a Python with working pip (skip Windows Store stubs)
PYTHON_CMD=""
for candidate in python py python3; do
    if command -v "$candidate" &>/dev/null 2>&1; then
        # Verify Python 3.8+ and not a Windows Store stub
        if "$candidate" -c "import sys, pathlib; assert sys.version_info >= (3,8)" &>/dev/null 2>&1; then
            # Check for working pip environment
            if "$candidate" -m pip --version &>/dev/null 2>&1; then
                PYTHON_CMD="$candidate"
                break
            fi
        fi
    fi
done

# -- Detect pip --
PIP_CMD=""
for candidate in pip pip3; do
    if command -v "$candidate" &>/dev/null 2>&1; then
        PIP_CMD="$candidate"
        break
    fi
done

# -- Detect OS --
case "$(uname -s 2>/dev/null)" in
    MINGW*|MSYS*|CYGWIN*|*NT*) OS_NAME="windows" ;;
    Darwin*)                     OS_NAME="macos"   ;;
    Linux*)                      OS_NAME="linux"   ;;
    *)                           OS_NAME="unknown"  ;;
esac

# -- Write local-env.sh --
cat > "$ENV_FILE" << ENVEOF
# Auto-generated by detect-env.sh — DO NOT EDIT
# Re-run: bash ~/.claude/scripts/detect-env.sh
export CLAUDE_PYTHON="${PYTHON_CMD:-python}"
export CLAUDE_PIP="${PIP_CMD:-pip}"
export CLAUDE_OS="${OS_NAME}"
ENVEOF

echo "[detect-env] Python=${PYTHON_CMD:-NOT FOUND}, pip=${PIP_CMD:-NOT FOUND}, OS=${OS_NAME}"
echo "[detect-env] Saved to ${ENV_FILE}"
